
# we define this variable in order to be set from the caller
# program if a different input file name is desired
input='hol-loading-output-redirection.txt' 

holchart:
	gawk -f holchart-maker.awk ${input} > holchart.txt
